require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', deterministic_uuids: false

target 'ReactNativeIdnowVideoidentExample' do
    config = use_native_modules!

    # Flags change depending on the env values.
    flags = get_default_flags

    use_react_native!(
        path: config[:reactNativePath],
        # Hermes is now enabled by default. Disable by setting this flag to false.
        # Upcoming versions of React Native may rely on get_default_flags(), but
        # we make it explicit here to aid in the React Native upgrade process.
        hermes_enabled: true,
        fabric_enabled: flags[:fabric_enabled],
        # Enables Flipper.
        #
        # Note that if you have use_frameworks! enabled, Flipper will not work and
        # you should disable the next line.
        flipper_configuration: FlipperConfiguration.disabled,
        # An absolute path to your application root.
        app_path: "#{Pod::Config.instance.installation_root}/.."
    )

    pod 'tokenstreet-react-native-idnow-videoident', path: '../../..'

    target 'ReactNativeIdnowVideoidentExampleTests' do
        inherit! :complete
        # Pods for testing
    end

    $static_library = %w[IDnowSDK Masonry SocketRocket libPhoneNumber-iOS FLAnimatedImage AFNetworking]

    pre_install do |installer|
        Pod::Installer::Xcode::TargetValidator.send(
            :define_method,
            :verify_no_static_framework_transitive_dependencies
        ) {}
        installer.pod_targets.each do |pod|
            bt = pod.send(:build_type)
            if $static_library.include?(pod.name)
                puts "Overriding the build_type to static_framework from from for #{pod.name}"
                def pod.build_type
                    Pod::BuildType.static_framework
                end
            end
        end
        installer.pod_targets.each do |pod|
            bt = pod.send(:build_type)
            puts "#{pod.name} (#{bt})"
            puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
        end
    end

    post_install do |installer|
        react_native_post_install(
            installer,
            # Set `mac_catalyst_enabled` to `true` in order to apply patches
            # necessary for Mac Catalyst builds
            mac_catalyst_enabled: false
        )
        __apply_Xcode_12_5_M1_post_install_workaround(installer)

        # Mandatory for M1 Macs to work together with `use_frameworks! linkage: :static`
        installer.pods_project.build_configurations.each do |config|
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
    end
end
