# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 15
    - package-ecosystem: 'gradle'
      directory: '/android'
      schedule:
          interval: 'weekly'
    - package-ecosystem: 'npm'
      directory: '/examples/bare'
      schedule:
          interval: 'weekly'
    - package-ecosystem: 'gradle'
      directory: '/examples/bare/android'
      schedule:
          interval: 'weekly'
      ignore:
          - dependency-name: 'idnow-android-sdk'
    - package-ecosystem: 'npm'
      directory: '/examples/expo'
      schedule:
          interval: 'weekly'
      ignore:
          - dependency-name: 'react'
          - dependency-name: 'react-native'
    - package-ecosystem: 'npm'
      directory: '/website'
      schedule:
          interval: 'weekly'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
