# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Root
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'

    # Core
    - package-ecosystem: 'npm'
      directory: '/packages/core'
      schedule:
          interval: 'daily'
    - package-ecosystem: 'gradle'
      directory: '/packages/core/android'
      schedule:
          interval: 'daily'

    # Example
    - package-ecosystem: 'npm'
      directory: '/packages/example'
      schedule:
          interval: 'daily'
    - package-ecosystem: 'bundler'
      directory: '/packages/example'
      schedule:
          interval: 'daily'
    - package-ecosystem: 'gradle'
      directory: '/packages/example/android'
      schedule:
          interval: 'daily'
      ignore:
          - dependency-name: 'idnow-android-sdk'

    # Shared
    - package-ecosystem: 'npm'
      directory: '/packages/shared'
      schedule:
          interval: 'daily'

    # Website
    - package-ecosystem: 'npm'
      directory: '/packages/website'
      schedule:
          interval: 'daily'
