root: true
parser: '@typescript-eslint/parser'
parserOptions:
    project:
        - './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - prettier
    - simple-import-sort
extends:
    - '@react-native-community'
    - eslint:all
    - plugin:@typescript-eslint/all
    - prettier
rules:
    '@typescript-eslint/array-type':
        - 2
        - default: 'generic'
    '@typescript-eslint/init-declarations': 0 # Worsens the structure
    '@typescript-eslint/lines-between-class-members': 0 # Worsens the structure
    '@typescript-eslint/no-confusing-void-expression':
        - 2
        - ignoreArrowShorthand: true
    '@typescript-eslint/no-empty-interface': 0 # Worsens the structure
    '@typescript-eslint/no-magic-numbers': 0 # Worsens the structure
    capitalized-comments: 0 # Worsens the structure
    line-comment-position: 0 # Worsens the structure
    max-lines-per-function: 0 # Worsens the structure
    no-inline-comments: 0 # Worsens the structure
    no-magic-numbers: 0 # Worsens the structure
    no-ternary: 0 # Worsens the structure
    no-undefined: 0 # Sometimes necessary
    one-var: 0 # Worsens the structure
    prefer-object-has-own: 0 # https://github.com/microsoft/TypeScript/issues/44253
    simple-import-sort/exports: 2 # Enabling the plugin simple-import-sort
    simple-import-sort/imports: 2 # Enabling the plugin simple-import-sort
    sort-imports: 0 # We already use the simple-import-sort plugin

    '@typescript-eslint/explicit-function-return-type': 0
    '@typescript-eslint/naming-convention': 0
    '@typescript-eslint/no-require-imports': 0
    '@typescript-eslint/no-unsafe-assignment': 0
    '@typescript-eslint/no-unsafe-call': 0
    '@typescript-eslint/no-var-requires': 0
    '@typescript-eslint/prefer-readonly-parameter-types': 0
    '@typescript-eslint/restrict-template-expressions': 0
    'require-unicode-regexp': 0
    multiline-comment-style: 0
    sort-keys: 0
