export enum IosEnvironmentEnum {
    IDnowEnvironmentNotDefined = 'IDnowEnvironmentNotDefined',
    IDnowEnvironmentDev = 'IDnowEnvironmentDev',
    IDnowEnvironmentDev0 = 'IDnowEnvironmentDev0',
    IDnowEnvironmentDev1 = 'IDnowEnvironmentDev1',
    IDnowEnvironmentDev2 = 'IDnowEnvironmentDev2',
    IDnowEnvironmentDev3 = 'IDnowEnvironmentDev3',
    IDnowEnvironmentDev4 = 'IDnowEnvironmentDev4',
    IDnowEnvironmentDev5 = 'IDnowEnvironmentDev5',
    IDnowEnvironmentTest = 'IDnowEnvironmentTest',
    IDnowEnvironmentTest1 = 'IDnowEnvironmentTest1',
    IDnowEnvironmentTest2 = 'IDnowEnvironmentTest2',
    IDnowEnvironmentTest3 = 'IDnowEnvironmentTest3',
    IDnowEnvironmentLive = 'IDnowEnvironmentLive',
    IDnowEnvironmentIntrum = 'IDnowEnvironmentIntrum',
    IDnowEnvironmentIntrumTest = 'IDnowEnvironmentIntrumTest',
    IDnowEnvironmentCustom = 'IDnowEnvironmentCustom',
}
