import type { ISettings } from '@tokenstreet/react-native-idnow-videoident';
import { Appearance } from 'react-native';

const isDarkMode = Appearance.getColorScheme() === 'dark';
const tokenstreetColors = {
    blue: '#2172f2',
    successColor: '#2d6c6e',
    failureColor: '#e94d41',
    white: '#ffffff',
    fontDarkGrey: '#282828',
    fontSemiDarkGrey: '#454545',
};

export const createFullSettings = (transactionToken: string): ISettings => ({
    transactionToken,
    ignoreCompanyID: true,
    companyId: undefined,
    environment: undefined,
    connectionType: undefined,
    language: undefined,
    locale: undefined,
    newLocale: undefined,
    disableLogging: undefined,
    callFromHighCallVolumeActivity: undefined,
    calledFromIDnowApp: undefined,
    allowInvalidCertificates: undefined,
    allowHttpConnections: undefined,
    checkScreenLinesLong: undefined,
    checkScreenBoxPhoneNumberRequired: undefined,
    checkScreenBoxDocumentRequired: undefined,
    checkScreenBoxEMailRequired: undefined,
    checkScreenBoxConsentRequired: undefined,
    phoneNo: undefined,
    showDialogsWithIcon: undefined,
    firebaseToken: undefined,
    showRatingDialog: undefined,
    forcedWaitingList: undefined,
    startCallIssued: undefined,
    overrideEntryActivity: undefined,
    appGoogleRating: undefined,
    apiHost: undefined,
    webHost: undefined,
    websocketHost: undefined,
    videoHost: undefined,
    stunHost: undefined,
    stunPort: undefined,
    appearance: {
        showVideoOverviewCheck: true,
        showErrorSuccessScreen: false,
        nameForActionBar: undefined,
        checkBoxOrientationRight: undefined,
        customiseCallQualityCheckScreen: undefined,
        showTokenDuringCheckScreen: undefined,
        squareCheckboxForm: undefined,
        agbInOneLine: undefined,
        checkboxesOrientationTop: undefined,
        doNotShowCompanyImageInResultActivity: undefined,
        headerBolded: undefined,
        fullSizeModalSmsWindow: undefined,
        transparentBackgroundModalSmsWindow: undefined,
        whiteAgentThumbnailBackground: undefined,
        mode: undefined,
        textFieldCornerRadius: undefined,
        useTitleSeparator: undefined,
        titleBackgroundImageOffset: undefined,
        resultButtonsAsUIButtonsBelow: undefined,
        useResultIcon: undefined,
        checkBoxPosition: undefined,
        shouldShowGTCInline: undefined,
        numberLabelPosition: undefined,
        seperatorLineComplete: undefined,
        markMandatoryCells: undefined,
        underlineButtonTitles: undefined,
        boldButtonTitles: undefined,
        boldTitles: undefined,
        requestCodeAgainLayoutType: undefined,
        checkBoxesSquared: undefined,
        inputFieldsSquared: undefined,
        identCodeLayoutHalf: undefined,
        newBranding: undefined,
        enableStatusBarStyleLightContent: false,
        fontNameBold: undefined,
        fontNameRegular: undefined,
        fontNameMedium: undefined,
        fontNameLight: undefined,
        shouldShowBlurOverlayLayer: undefined,
        alphaBlurViewValue: undefined,
        lightBlurForIdentCodeContainer: undefined,
        shouldShowNavigationBarOnCQCScreen: undefined,
        shouldUseHeadlineColorForPreCheckTitle: undefined,
        progressBarsSquared: undefined,
        shouldShowResultTitleForCQCResult: undefined,
        shouldShowNetworkIndicatorForCQCResult: undefined,
        recheckButtonsBordered: undefined,
        shouldSeparateFooter: undefined,
        suggestionListBulleted: undefined,
        colors: {
            defaultTextColor: isDarkMode ? tokenstreetColors.white : tokenstreetColors.fontDarkGrey,
            primaryBrandColor: tokenstreetColors.blue,
            headlineColor: undefined,
            linkColor: undefined,
            checkIconColor: undefined,
            proceedButtonBackgroundColor: tokenstreetColors.blue,
            proceedButtonTextColor: tokenstreetColors.white,
            photoIdentRetakeButtonBackgroundColor: tokenstreetColors.blue,
            photoIdentRetakeButtonTextColor: tokenstreetColors.white,
            checkContractFooterButtonBackgroundColor: undefined,
            checkContractFooterButtonTextColor: undefined,
            textFieldColor: isDarkMode ? tokenstreetColors.white : tokenstreetColors.fontSemiDarkGrey,
            textFieldBorderColor: undefined,
            failureColor: tokenstreetColors.failureColor,
            successColor: tokenstreetColors.successColor,
            titleBackgroundColor: undefined,
            resultScreenHeaderLabelColor: undefined,
            backgroundColor: undefined,
            cqcOuterRingColor: undefined,
            cqcDefaultInnerRingColor: undefined,
            cqcPoorQualityInnerColor: undefined,
            cqcModerateQualityInnerColor: undefined,
            cqcExcellentQualityInnerColor: undefined,
        },
    },
});
