import type { ISettings } from '@tokenstreet/react-native-idnow-videoident';
import {
    AndroidLanguageEnum,
    ConnectionTypeEnum,
    IosCheckboxPositionEnum,
    IosNumberLabelPositionEnum,
    IosRequestCodeAgainLayoutTypeEnum,
} from '@tokenstreet/react-native-idnow-videoident';
import { Appearance } from 'react-native';

import type { DeepRequired } from './DeepRequired';

const getCurrentThemeColor = (lightColor: string, darkColor: string): string =>
    Appearance.getColorScheme() === 'light' ? lightColor : darkColor;
const tokenstreetColors = {
    black: '#000000',
    blue: '#2172f2',
    failureColor: '#e94d41',
    fontDarkGrey: '#282828',
    fontSemiDarkGrey: '#454545',
    green: '#2d6c6e',
    red: '#e94d41',
    successColor: '#2d6c6e',
    white: '#ffffff',
    yellow: '#f9db61',
};
const themeColors = {
    backgroundColor: getCurrentThemeColor(tokenstreetColors.white, tokenstreetColors.black),
    textColor: getCurrentThemeColor(tokenstreetColors.fontDarkGrey, tokenstreetColors.white),
};

export const createFullSettings = (transactionToken: string): DeepRequired<ISettings> => ({
    allowHttpConnections: false,
    allowInvalidCertificates: false,
    apiHost: '',
    appGoogleRating: false,
    appearance: {
        agbInOneLine: false,
        alphaBlurViewValue: 1.0,
        boldButtonTitles: true,
        boldTitles: false,
        checkBoxOrientationRight: false,
        checkBoxPosition: IosCheckboxPositionEnum.LEFT,
        checkBoxesSquared: false,
        checkboxesOrientationTop: false,
        colors: {
            backgroundColor: themeColors.backgroundColor,
            checkContractFooterButtonBackgroundColor: tokenstreetColors.blue,
            checkContractFooterButtonTextColor: tokenstreetColors.white,
            checkIconColor: undefined,
            cqcDefaultInnerRingColor: undefined,
            cqcExcellentQualityInnerColor: tokenstreetColors.green,
            cqcModerateQualityInnerColor: tokenstreetColors.yellow,
            cqcOuterRingColor: undefined,
            cqcPoorQualityInnerColor: tokenstreetColors.red,
            defaultTextColor: themeColors.textColor,
            failureColor: tokenstreetColors.failureColor,
            headlineColor: undefined,
            linkColor: tokenstreetColors.blue,
            photoIdentRetakeButtonBackgroundColor: tokenstreetColors.blue,
            photoIdentRetakeButtonTextColor: tokenstreetColors.white,
            primaryBrandColor: tokenstreetColors.blue,
            proceedButtonBackgroundColor: tokenstreetColors.blue,
            proceedButtonTextColor: tokenstreetColors.white,
            resultScreenHeaderLabelColor: undefined,
            successColor: tokenstreetColors.successColor,
            textFieldBorderColor: undefined,
            textFieldColor: getCurrentThemeColor(tokenstreetColors.fontSemiDarkGrey, tokenstreetColors.white),
            titleBackgroundColor: undefined,
        },
        customiseCallQualityCheckScreen: false,
        doNotShowCompanyImageInResultActivity: undefined,
        enableStatusBarStyleLightContent: false,
        fontNameBold: '',
        fontNameLight: '',
        fontNameMedium: '',
        fontNameRegular: '',
        fullSizeModalSmsWindow: false,
        headerBolded: undefined,
        identCodeLayoutHalf: false,
        inputFieldsSquared: false,
        lightBlurForIdentCodeContainer: undefined,
        markMandatoryCells: false,
        mode: undefined,
        nameForActionBar: 'Action bar name',
        newBranding: true,
        numberLabelPosition: IosNumberLabelPositionEnum.LABELLEFT,
        progressBarsSquared: false,
        recheckButtonsBordered: undefined,
        requestCodeAgainLayoutType: IosRequestCodeAgainLayoutTypeEnum.BOTTOM,
        resultButtonsAsUIButtonsBelow: false,
        seperatorLineComplete: false,
        shouldSeparateFooter: false,
        shouldShowBlurOverlayLayer: false,
        shouldShowGTCInline: undefined,
        shouldShowNavigationBarOnCQCScreen: undefined,
        shouldShowNetworkIndicatorForCQCResult: undefined,
        shouldShowResultTitleForCQCResult: undefined,
        shouldUseHeadlineColorForPreCheckTitle: undefined,
        showErrorSuccessScreen: true,
        showTokenDuringCheckScreen: true,
        showVideoOverviewCheck: true,
        squareCheckboxForm: undefined,
        suggestionListBulleted: undefined,
        textFieldCornerRadius: 4.0,
        titleBackgroundImageOffset: undefined,
        transparentBackgroundModalSmsWindow: true,
        underlineButtonTitles: true,
        useResultIcon: true,
        useTitleSeparator: undefined,
        whiteAgentThumbnailBackground: undefined,
    },
    callFromHighCallVolumeActivity: undefined,
    calledFromIDnowApp: false,
    checkScreenBoxConsentRequired: true,
    checkScreenBoxDocumentRequired: undefined,
    checkScreenBoxEMailRequired: false,
    checkScreenBoxPhoneNumberRequired: false,
    checkScreenLinesLong: undefined,
    companyId: undefined,
    connectionType: ConnectionTypeEnum.WEBSOCKET,
    disableLogging: false,
    environment: undefined,
    firebaseToken: '',
    forcedWaitingList: undefined,
    ignoreCompanyID: true,
    language: AndroidLanguageEnum.EN,
    locale: AndroidLanguageEnum.EN,
    newLocale: AndroidLanguageEnum.EN,
    overrideEntryActivity: undefined,
    phoneNo: undefined,
    showDialogsWithIcon: undefined,
    showRatingDialog: undefined,
    startCallIssued: undefined,
    stunHost: '',
    stunPort: 0,
    transactionToken,
    videoHost: '',
    webHost: '',
    websocketHost: '',
});
