name: Pull request

on:
    pull_request:
        branches:
            - main

jobs:
    yarn_script_validation:
        name: yarn script validation
        runs-on: ubuntu-latest
        strategy:
            matrix:
                script: [typescript, lint, test, build]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3.1.1
              with:
                  node-version: 16
                  cache: yarn
            - run: yarn install
            # - run: yarn install --frozen-lockfile
            - run: yarn ${{ matrix.script }}
