name: Pull request

on:
    pull_request:
        branches:
            - main

jobs:
    yarn_script_validation:
        name: yarn script validation
        runs-on: ubuntu-latest
        strategy:
            matrix:
                VALIDATION: [TypeScript, ESLint, Tests, Buildable]
                include:
                    - VALIDATION: TypeScript
                      COMMAND: typescript
                    - VALIDATION: ESLint
                      COMMAND: lint
                    - VALIDATION: Tests
                      COMMAND: test
                    - VALIDATION: Buildable
                      COMMAND: build
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3.1.1
              with:
                  node-version: 16
                  cache: yarn
            - run: |
                  yarn install --frozen-lockfile
                  yarn install --cwd website --frozen-lockfile
                  yarn build
                  yarn install --cwd example --frozen-lockfile
            - run: yarn ${{ matrix.COMMAND }}
